# Generated by Django 5.0.6 on 2024-06-23 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WellnessScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical', models.IntegerField(default=0)),
                ('intellectual', models.IntegerField(default=0)),
                ('mental', models.IntegerField(default=0)),
                ('social', models.IntegerField(default=0)),
                ('spiritual', models.IntegerField(default=0)),
                ('occupational', models.IntegerField(default=0)),
                ('emotional', models.IntegerField(default=0)),
                ('financial', models.IntegerField(default=0)),
                ('environmental', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.user')),
            ],
        ),
    ]
